name: Teste de Stealth

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Dependências
        run: |
          pip install playwright playwright-stealth PyGithub
          playwright install chromium
          playwright install-deps

      - name: Rodar script de teste
        run: python verificador.py

      - name: Upload Debug Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: debug-stealth-results
          path: |
            debug_espelho.txt
            debug_visual.png
