name: Atualizador

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar Playwright e Dependências
        run: |
          pip install playwright PyGithub playwright-stealth
          playwright install chromium
          playwright install-deps

      - name: Rodar script
        env:
          MEU_TOKEN_GITHUB: ${{ secrets.MEU_TOKEN_GITHUB }}
        run: python verificadorplay.py

      - name: Salvar screenshots em caso de erro
        if: always()  # Isso garante que ele tente salvar mesmo se o script falhar
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshots
          path: "*.png"
